name: Publish Test Website

on:
  push:
    branches: [dev]

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: ubuntu-latest
      - uses: enriikke/gatsby-gh-pages-actions@v2.1.1
        with:
          access-token: ${{ secrets.DEPLOY_TEST_SITE }}
          deploy-branch: master
